server:
  port: 8080

spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/linkermsrdb'
    username: 'linkermsru'
    password: 'linkermsr'
  jpa:
    open-in-view: false

controller:
  advice:
    response:
      provideMessage: true
      message:
        placeholder: ""
        default: "Internal server error."
  balance:
    path: "/balance"

text:
  exception:
    balanceNotFound: "The balance with ID %1$s was not found."
    balanceExists: "The balance with ID %1$s already exists."
    balanceIdNull: "The provided ID is null."
