#Defailt application port
server:
  port: 8080

# Spring settings
spring:
  # PostgreSQL
  datasource:
    url: 'jdbc:postgresql://localhost:5432/linkermsrdb'
    username: 'linkermsru'
    password: 'linkermsr'
  # JPA
  jpa:
    open-in-view: false
  # Logger
  profiles:
    active: 'development'
  cache:
    couchbase:
      expiration: 60000

# Logger config
logging:
  file:
    path: 'logs'

# Custom controller properties
controller:
  # Main controller advice properties
  advice:
    response:
      provideMessage: true
      message:
        placeholder: ""
        default: "Internal server error."
  # Balance controller properties
  balance:
    path: "/balance"